name: C++ Build

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile files
      run: |
        g++ QueueWithLinkedList.cpp -o queue
        g++ StackWithLinkedList.cpp -o stack
        g++ Stack_Queue_Using_LinkedList.cpp -o stackqueue
        g++ linkedlist.cpp -o linkedlist
        g++ linkedlist2.cpp -o linkedlist2
