name: C++ Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile project
      run: |
        g++ src/main.cpp src/Stack.cpp src/Queue.cpp -o airline
